# Generated by Django 5.0 on 2023-12-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("apartment", "Apartment"),
                            ("mansion", "Mansion"),
                        ],
                        default="home",
                        max_length=15,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
                ("pin_code", models.CharField(max_length=10)),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="property_features", to="properties.feature"
                    ),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("1bhk", "1BHK"),
                            ("2bhk", "2BHK"),
                            ("3bhk", "3BHK"),
                            ("4bhk", "4BHK"),
                        ],
                        default="1bhk",
                        max_length=7,
                    ),
                ),
                ("rent_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=10,
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="unit_features", to="properties.feature"
                    ),
                ),
                (
                    "property_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
