# Generated by Django 5.0 on 2023-12-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_image",
            field=models.ImageField(
                default="/media/properties/Homepage_desktop_b6361fc52d.jpg",
                upload_to="properties/",
            ),
        ),
    ]
